### PR TITLE
Vm 0.50,  working rpm spec file

### PR DESCRIPTION
**Pull request by jmrcpn**
I would like to experiment/play with UCSD-Psystem on Linux
(I worked/played a lot with UCSD pascal on apple-II,.... long time ago)
I added an rpm spec file to be able to install the package
on osukiss (linux distribustion)

I do not know how to do to validate package build
meson test -C _bld

Your input and advices are welcome.

Hopefully you will find my contribution good enough to be merged
within your repository.

### CODE REVIEW

**Comment by jdykstra** [comment]
Hello, Jean-Marc!  Thank you for creating this RPM spec file.  I’ll try to address your meson build question in the next couple of days, but please be patient…I’m juggling a lot of things right now.

  —  John

**Comment by jdykstra** [comment]
> I would like to experiment/play with UCSD-Psystem on Linux (I worked/played a lot with UCSD pascal on apple-II,.... long time ago) I added an rpm spec file to be able to install the package on osukiss (linux distribustion)

An RPM spec file is needed only if you intend to submit this project for possible inclusion in future osukiss releases.  Is that your intention?

> I do not know how to do to validate package build meson test -C _bld

A github issue is probably the best way to discuss this.  Please open one, describing what you're encountering when you do the "meson test" command.  

Thanks - John

**Comment by jmrcpn** [comment]
On Thu, 2024-10-17 at 12:11 -0700, John Dykstra wrote:
> > I would like to experiment/play with UCSD-Psystem on Linux (I
> > worked/played a lot with UCSD pascal on apple-II,.... long time
> > ago) I added an rpm spec file to be able to install the package on
> > osukiss (linux distribustion)
> An RPM spec file is needed only if you intend to submit this project
> for possible inclusion in future osukiss releases. Is that your
> intention?
Yes,...  but beyond that, rpm spec file give you the way to
recompile/install procedure
an the rpm can be easily (or rebuild for another distribution) on a 
plain system (pratical and convenient)
> > I do not know how to do to validate package build meson test -C
> > _bld

> 
> A github issue is probably the best way to discuss this. Please open
> on, describing what you're encountering when you do the "meson test"
> command.
I resolved the test problems as caused by dependencies missing.
Among the 4 ucsd-psystem only one test is not 100% succesful

ucsd-psystem-xc
585/590 t0736a FAIL 0.04s exit status 2

Ok: 589 
Expected Fail: 0 
Fail: 1 
Unexpected Pass: 0 
Skipped: 0 
Timeout: 0 

No idea why this this test fail...

Beside that.
ucsd-psystem-vm is working fine...
Tried to recompile P5.pas, not sucessful,
after (around) 355 lines the compilation
stop (forever), the only way to recover
is to kill the process.

Was somebody success full to recompile
something meaningful via ucsd-psystem-vm?

Thanks for you help.
> Thanks - John
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

-- 
A bientôt

Jean-Marc Pigeon ***@***.***>
SAFE Inc.

**Comment by jdykstra** [comment]
> Yes,...  but beyond that, rpm spec file give you the way to recompile/install procedure an the rpm can be easily (or rebuild for another distribution) on a  plain system (pratical and convenient)

I prefer to follow the lead of GNU and other open source projects and keep distribution-specific files out of this repo.  Following the existing BUILDING instructions is not onerous.  If we did add an RPM spec file, it should use `meson` rather than `make`.  We've already crossed that bridge and we're not going back.

FWIW, trying your PR on a clean Fedora Workstation 40 image resulted in:
```
jwd@fedora:~/pr/ucsd-psystem-vm$ make spec
fatal: bad revision '^tag-master'
```
> Among the 4 ucsd-psystem only one test is not 100% succesful ucsd-psystem-xc 585/590 t0736a FAIL 0.04s exit status 2 Ok: 589 Expected Fail: 0 Fail: 1 Unexpected Pass: 0 Skipped: 0 Timeout: 0 No idea why this this test fail... 

I'll take a look at that.  I sort of remember that there was one failing test, but if so, I should have documented that in an issue.

> Beside that. ucsd-psystem-vm is working fine... Tried to recompile P5.pas, not sucessful, after (around) 355 lines the compilation stop (forever), the only way to recover is to kill the process. Was somebody success full to recompile something meaningful via ucsd-psystem-vm? Thanks for you help.

I have mainly used  the vm to run the UCSD assembler.  I've got no idea what experiences others have had--feedback has been minimal.  There are subtle compatibility problems between the VM and CODE and SYSTEM files from various sources that I have not had the time to analyze.  Note that the Apple II variant of the UCSD P-system was definitely different than releases for other platforms.

**Comment by jdykstra** [comment]
Also, your mod to .gitignore deletes all of its previous contents.

**Comment by jmrcpn** [comment]
On Sun, 2024-10-20 at 15:48 -0700, John Dykstra wrote:
> > Yes,... but beyond that, rpm spec file give you the way to
> > recompile/install procedure an the rpm can be easily (or rebuild
> > for another distribution) on a plain system (pratical and
> > convenient)
> I prefer to follow the lead of GNU and other open source projects and
> keep distribution-specific files out of this repo. Following the
> existing BUILDING instructions is not onerous. If we did add an RPM
> spec file, it should use meson rather than make. We've already
> crossed that bridge and we're not going back.
The spec file is indeed using meson to build+install the the binary
file,
make rpmbin:
generate  a file named:
ucsd-psystem-vm-0.50.8-safe.x86_64.rpm
ready to be installed+used on a linux system.
> FWIW, trying your PR on a clean Fedora Workstation 40 image resulted
> in:
> ***@***.***:~/pr/ucsd-psystem-vm$ make spec
> fatal: bad revision '^tag-master'

I do not confirm. On my side:
git clone https://github.com/jmrcpn/ucsd-psystem-vm.git xxx
cd xxx
git checkout vm-0.50
make spec

No trouble using this sequence, ucsd-psystem-vm.spec
file is properly generated.
Git version is 2.46, the fact it is not done 
on fedora should not matter to generate
the rpm file.
(what am I missing here?).
> > Among the 4 ucsd-psystem only one test is not 100% succesful ucsd-
> > psystem-xc 585/590 t0736a FAIL 0.04s exit status 2 Ok: 589 Expected
> > Fail: 0 Fail: 1 Unexpected Pass: 0 Skipped: 0 Timeout: 0 No idea
> > why this this test fail...
> I'll take a look at that. I sort of remember that there was one
> failing test, but if so, I should have documented that in an issue.
At first glance, (just my feeling, I didn't prove it), uuencode is
needed within
that test and I do not have uuencode avail on my ucsd compiling server.

> > Beside that. ucsd-psystem-vm is working fine... Tried to recompile
> > P5.pas, not sucessful, after (around) 355 lines the compilation
> > stop (forever), the only way to recover is to kill the process. Was
> > somebody success full to recompile something meaningful via ucsd-
> > psystem-vm? Thanks for you help.
> I have mainly used the vm to run the UCSD assembler. I've got no idea
> what experiences others have had--feedback has been minimal. There
> are subtle compatibility problems between the VM and CODE and SYSTEM
> files from various sources that I have not had the time to analyze.
> Note that the Apple II variant of the UCSD P-system was definitely
> different than releases for other platforms.
Compiling whatever Pascal language version, should return multiple
errors
not "freeze' the vm.
My feeling, it is ressource problem (stack size, global memory space..)
within
the vm
The way I am using ucsd-psystem-vm,  I do not have  xterm available, so
I may
be missing crucial log or report about the "freeze" situation. 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

-- 
A bientôt

Jean-Marc Pigeon ***@***.***>
SAFE Inc.

**Comment by jmrcpn** [comment]
Bonjour John,


On Sun, 2024-10-20 at 15:50 -0700, John Dykstra wrote:
> Also, your mod to .gitignore deletes all of its previous contents.
Could you tell more?? 😏️, no idea what you are meaning...
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

-- 
A bientôt

Jean-Marc Pigeon ***@***.***>
SAFE Inc.

**Comment by jmrcpn** [comment]
Bonjour John,

Quick Updates...
On Sun, 2024-10-20 at 15:48 -0700, John Dykstra wrote:
> > Yes,... but beyond that, rpm spec file give you the way to
> > recompile/install procedure an the rpm can be easily (or rebuild
> > for another distribution) on a plain system (pratical and
> > convenient)
> I prefer to follow the lead of GNU and other open source projects and
> keep distribution-specific files out of this repo. Following the
> existing BUILDING instructions is not onerous. If we did add an RPM
> spec file, it should use meson rather than make. We've already
> crossed that bridge and we're not going back.
> FWIW, trying your PR on a clean Fedora Workstation 40 image resulted
> in:
> ***@***.***:~/pr/ucsd-psystem-vm$ make spec
> fatal: bad revision '^tag-master'
I double check this morning on a fedora-41
Make spec 
is indeed properly working provided you are on branch vm-0.50.
> > Among the 4 ucsd-psystem only one test is not 100% succesful ucsd-
> > psystem-xc 585/590 t0736a FAIL 0.04s exit status 2 Ok: 589 Expected
> > Fail: 0 Fail: 1 Unexpected Pass: 0 Skipped: 0 Timeout: 0 No idea
> > why this this test fail...
I do confirm problem about test t0736a failling was caused by uuencode
missing
on my testbench.
Once dependency to sharutils set within spec file, everything went
fine.
> 
> I'll take a look at that. I sort of remember that there was one
> failing test, but if so, I should have documented that in an issue.
> > Beside that. ucsd-psystem-vm is working fine... Tried to recompile
> > P5.pas, not sucessful, after (around) 355 lines the compilation
> > stop (forever), the only way to recover is to kill the process. Was
> > somebody success full to recompile something meaningful via ucsd-
> > psystem-vm? Thanks for you help.
> I have mainly used the vm to run the UCSD assembler. I've got no idea
> what experiences others have had--feedback has been minimal. There
> are subtle compatibility problems between the VM and CODE and SYSTEM
> files from various sources that I have not had the time to analyze.
> Note that the Apple II variant of the UCSD P-system was definitely
> different than releases for other platforms.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

-- 
A bientôt

Jean-Marc Pigeon ***@***.***>
SAFE Inc.

**Comment by jdykstra** [comment]
>>On Sun, 2024-10-20 at 15:48 -0700, John Dykstra wrote: > If we did add an RPM spec file, it should use meson rather than make. We've already crossed that bridge and we're not going back.

>The spec file is indeed using meson to build+install the the binary file, make rpmbin: generate  a file named: ucsd-psystem-vm-0.50.8-safe.x86_64.rpm ready to be installed+used on a linux system.

But you're using make to create the RPM spec file.  That is what I'm objecting to.

>> FWIW, trying your PR on a clean Fedora Workstation 40 image resulted in: ***@***.***:~/pr/ucsd-psystem-vm$ make spec fatal: bad revision '^tag-master'
> I do not confirm. On my side: git clone https://github.com/jmrcpn/ucsd-psystem-vm.git xxx cd xxx git checkout vm-0.50 make spec No trouble using this sequence, ucsd-psystem-vm.spec file is properly generated. Git version is 2.46, the fact it is not done  on fedora should not matter to generate the rpm file. (what am I missing here?).

Your Makefile.git assumes a particular format for branch names, with a version number at the end.  Your fork branch follows that convention, but the upstream repo (this one) does not.

> Beside that. ucsd-psystem-vm is working fine... Tried to recompile 
> P5.pas, not sucessful, after (around) 355 lines the compilation stop (forever), the only way to recover is to kill the process.  ,,,  Compiling whatever Pascal language version, should return multiple errors not "freeze' the vm. My feeling, it is ressource problem (stack size, global memory space..) within the vm The way I am using ucsd-psystem-vm,  

P5 is much bigger than most of the programs that were compiled and run on UCSD Pascal,  and it probably stresses both the VM and the UCSD compiler in ways they were never stressed back in the day.  Please open an issue here on Github to document the problem, but I can't promise that I'll try to fix it.

> Yes,... but beyond that, rpm spec file give you the way to
 > recompile/install procedure an the rpm can be easily (or rebuild
 > for another distribution) on a plain system (pratical and
 > convenient)

I still don't understand the use case underlying this PR.  RPM spec files and other distribution-specific items don't belong in the upstream project.  In addition, Fedora and most of its derivatives do not include libexplain, which is required by this  project.  Just adding a spec file isn't going to make the prerequisite challenges go away.

**Comment by jmrcpn** [comment]
> > > On Sun, 2024-10-20 at 15:48 -0700, John Dykstra wrote: > If we did add an RPM spec file, it should use meson rather than make. We've already crossed that bridge and we're not going back.
> 
> > The spec file is indeed using meson to build+install the the binary file, make rpmbin: generate  a file named: ucsd-psystem-vm-0.50.8-safe.x86_64.rpm ready to be installed+used on a linux system.
> 
> But you're using make to create the RPM spec file. That is what I'm objecting to.
> 
> > > FWIW, trying your PR on a clean Fedora Workstation 40 image resulted in: _**@**_.***:~/pr/ucsd-psystem-vm$ make spec fatal: bad revision '^tag-master'
> > > I do not confirm. On my side: git clone https://github.com/jmrcpn/ucsd-psystem-vm.git xxx cd xxx git checkout vm-0.50 make spec No trouble using this sequence, ucsd-psystem-vm.spec file is properly generated. Git version is 2.46, the fact it is not done  on fedora should not matter to generate the rpm file. (what am I missing here?).
> 
> Your Makefile.git assumes a particular format for branch names, with a version number at the end. Your fork branch follows that convention, but the upstream repo (this one) does not.
> 
> > Beside that. ucsd-psystem-vm is working fine... Tried to recompile
> > P5.pas, not sucessful, after (around) 355 lines the compilation stop (forever), the only way to recover is to kill the process.  ,,,  Compiling whatever Pascal language version, should return multiple errors not "freeze' the vm. My feeling, it is ressource problem (stack size, global memory space..) within the vm The way I am using ucsd-psystem-vm,
> 
> P5 is much bigger than most of the programs that were compiled and run on UCSD Pascal, and it probably stresses both the VM and the UCSD compiler in ways they were never stressed back in the day. Please open an issue here on Github to document the problem, but I can't promise that I'll try to fix it.
> 
> > Yes,... but beyond that, rpm spec file give you the way to
> > recompile/install procedure an the rpm can be easily (or rebuild
> > for another distribution) on a plain system (pratical and
> > convenient)
> 
> I still don't understand the use case underlying this PR. RPM spec files and other distribution-specific items don't belong in the upstream project. In addition, Fedora and most of its derivatives do not include libexplain, which is required by this project. Just adding a spec file isn't going to make the prerequisite challenges go away.

**Comment by jmrcpn** [comment]
Note:

I defined my "own" branch, as there is no proper/real tag versionning used in your repository.
Agreed rpm spec file are distribution specfic, but spec file are a very good starting point to
lookat when you want compile/try/debug/understand a project.

Long Long time ago, I wrote a self-bootable Yacc program on Apple-UCSD (generating pascal Language)
my apple-II was 64K, 2 disks(140K). On  UCSD-PSYSTEM-VM, pint is running on an harware with 
plenty of ressources, swapping was set in the compiler source header, so I was a little bit surprised
to see the compiler ending in a dead loop (May be I missed a pint configuration option flag).

**Pull request closed without merging**
